### ISSUE TITLE
Getting started

### ISSUE THREAD

**Issue by jbglaw** [kkaempf/ghidra#1]
Hi!

To not clutter the upstream PRs all that much, I'll continue here. So ... I can build Ghidra locally and switched over to your fork. Trying to keep the gradle binary confined, I'm building in Debian "unstable" Docker container with this script:

```
$ cat build_ghidra.sh 
#!/usr/bin/env bash

# This is the most recent Gradle release as of 20230629:
gradle_url="https://services.gradle.org/distributions/gradle-8.1.1-bin.zip"
gradle_file="$(basename "${gradle_url}"           )"
gradle_dir="$( basename "${gradle_url}" "-bin.zip")"

apt-get update
apt-get install -y wget unzip default-jdk gcc g++ git
apt-get clean

git clone https://github.com/kkaempf/ghidra-vintage.git

wget -O "${gradle_file}" --continue "${gradle_url}"
unzip -f "${gradle_file}"
pushd ghidra-vintage
        git pull --force
        sed -i -e 's#git@github.com:kkaempf#https://github.com/kkaempf#' .gitmodules
        git submodule init
        git submodule update

        "../${gradle_dir}/bin/gradle" -I gradle/support/fetchDependencies.gradle init
#       "../${gradle_dir}/bin/gradle" -Dfile.encoding=UTF-8 --project-prop finalRelease=true buildNatives_linux64
#       "../${gradle_dir}/bin/gradle" buildGhidra
        "../${gradle_dir}/bin/gradle" -Dfile.encoding=UTF-8 --project-prop finalRelease=true buildGhidra
        mv build/dist/ghidra*.zip ..
popd
```

That fixes a little issue with SSH access rights for your, as it shows up with `git@github.com` instead of `https://...`. Building seems to work, a ZIP is generated. However, it seems the two new CPUs (VAX and NMOS-II) are missing in the release file.

Copying over the supposedly missing files seems to be not enough: `Can't read language spec  /home/jbglaw/src/3rdparty/ghidra/extract/ghidra_10.4_DEV/Ghidra/Processors/VAX/data/languages/vax.sla`. That is probably ment to be compiled from the Processor's definition?

**Comment by jbglaw** [comment]
Played with it a little bit more.

Seems the build process does _not_ like the submodule, as it shows up as the `./Ghidra/Processors/VAX/`, but contains all files within another `./VAX/` directory, so we end up with two times `VAX` in the path.

For a test, I then moved all files from the `VAX` directory (within the submodule) to the submodule's root directory, but the `certification.manifest` doesn't match the actual filenames:
```
--- a/certification.manifest
+++ b/certification.manifest
@@ -1,7 +1,7 @@
 ##VERSION: 2.0
 Module.manifest||GHIDRA||||END|
-data/languages/VAX.cspec||GHIDRA||||END|
+data/languages/vax.cspec||GHIDRA||||END|
 data/languages/VAX.ldefs||GHIDRA||||END|
-data/languages/VAX.pspec||GHIDRA||||END|
-data/languages/VAX.slaspec||GHIDRA||||END|
+data/languages/vax.pspec||GHIDRA||||END|
+data/languages/vax.slaspec||GHIDRA||||END|
 data/manuals/VAX.idx||GHIDRA||||END|
```
With that fix, compilation fails with:
```
> Task :VAX:ip
> Task :VAX:saveSleighArgs

> Task :VAX:sleighCompile FAILED
Compiling ./data/languages/vax.slaspec:
vax.slaspec:330: Table 'eaw' has inconsistent export size; Constructor at vax.slaspec:330 is first conflict
vax.slaspec:280: Table 'eab' has inconsistent export size; Constructor at vax.slaspec:280 is first conflict
vax.slaspec:370: Table 'eal' has inconsistent export size; Constructor at vax.slaspec:370 is first conflict
vax.slaspec:371: Table 'eal' has inconsistent export size; Constructor at vax.slaspec:371 is first conflict
vax.slaspec:372: Table 'eal' has inconsistent export size; Constructor at vax.slaspec:372 is first conflict
vax.slaspec:373: Table 'eal' has inconsistent export size; Constructor at vax.slaspec:373 is first conflict
vax.slaspec:423: Table 'eaq' has inconsistent export size; Constructor at vax.slaspec:423 is first conflict
No output produced

0 languages successfully compiled
/home-host/src/3rdparty/ghidra/ghidra-vintage/Ghidra/Processors/VAX/./data/languages/vax.slaspec failed to compile
1 languages total failed to compile

FAILURE: Build failed with an exception.
```

Seems I need to read a bit about how a processor is represented in Ghidra to understand what's not working here.

**Comment by kkaempf** [comment]
(Just for the record)

> That fixes a little issue with SSH access rights for your, as it shows up with `git@github.com` instead of `https://...`. 

Yeah, sorry, 🤦🏻 
Fixed in https://github.com/kkaempf/ghidra-vintage/commit/595e04803978e8b4da3ab7d34726a059c3d28b1f

**Comment by kkaempf** [comment]
> 
> Copying over the supposedly missing files seems to be not enough: `Can't read language spec /home/jbglaw/src/3rdparty/ghidra/extract/ghidra_10.4_DEV/Ghidra/Processors/VAX/data/languages/vax.sla`. That is probably ment to be compiled from the Processor's definition?

This is probably due to a [missing commit](https://github.com/kkaempf/ghidra-vax/commit/1036c7ef6fac61ae9bd8ab831563c0b7fe81d127) - fixed meanwhile.

**Comment by kkaempf** [comment]
> Seems the build process does _not_ like the submodule, as it shows up as the `./Ghidra/Processors/VAX/`, but contains all files within another `./VAX/` directory, so we end up with two times `VAX` in the path.

See https://github.com/kkaempf/ghidra-vax/commit/1036c7ef6fac61ae9bd8ab831563c0b7fe81d127 (which I missed to push before 🤦🏻‍♂️ )

> 
> For a test, I then moved all files from the `VAX` directory (within the submodule) to the submodule's root directory, but the `certification.manifest` doesn't match the actual filenames:

Fixed in https://github.com/kkaempf/ghidra-vax/commit/034b26c33500169e0c9280562638daf432e56617

> 
> With that fix, compilation fails with:
> 
> ```
> vax.slaspec:330: Table 'eaw' has inconsistent export size; Constructor at vax.slaspec:330 is first conflict
> ...
> ```

This does not happen for me 🤔

**Comment by jbglaw** [comment]
With the new commits (not sure if even more showed up), I already have a working build and doin' my very first baby steps with Ghidra.

I found out how to set a `l`abel, how to set some address to a specific data `t`ype (eg. `word` for an entry mask) and let it `d`issassemble on the next (usually `subl` for some automatic variables) byte. I also can place some `;` comments here and there.

Now I need to find out how to use higher-level functions. I guess there's some way to mark some address as a function entry point properly (to eg. let it autodetect the register mask?) and to give it a meaningful function prototype. Also not too sure if `CASE*` instructions (or their jump tables) are properly dissected. But before looking at such details, I'd learn how to use at least the most basic functionality of Ghidra.

**Comment by kkaempf** [comment]
`CASE` is (mostly) handled correctly and even translates to a `switch` statement in C. Haven't found out yet why not all CASE statements are correctly recognized.

Missing is the detection of functions according to the VAX calling standard. This needs to go into the `cspec` file.

**Comment by kkaempf** [comment]
We might need to move this discussion to [ghidra-vax](https://github.com/kkaempf/ghidra-vax) instead 😉

**Comment by jbglaw** [comment]
Full ACK!
